### ISSUE TITLE
Clarification,  with issue on make build.

### ISSUE THREAD

**Issue by ericwhiteau** [tuanchris/cloud-data-lake#3]
Hello there,
first up thanks for your work in setting this up, it has helped me get a good understanding of Airflow with more than a simple configuration.

I am having trouble with "make build",  well the build is fine.  (I had to add a line to make the entrypoint.sh executable.)

Question:  should I be changing all the references in the docker-compose file to the image I built?  e.g.
from.....
worker:
        image: puckel/docker-airflow:1.10.9
to ....
worker:
        image: docker-airflow-cloud:latest

That is what I did.  but if I do that the system will no longer boot.  (see error below)  it shows an error flask_bcrypt,  But I have seen it build in the logs??
Is there an issue with me changing the name?  (I dropped lake off)?

Any help would be great.  thanks.

 | [2020-08-18 00:24:55,705] {{__init__.py:72}} CRITICAL - Cannot import airflow.contrib.auth.backends.password_auth for API authentication due to: No module named 'flask_bcrypt'
flower_1     | Traceback (most recent call last):
flower_1     |   File "/usr/local/lib/python3.7/site-packages/airflow/api/__init__.py", line 56, in load_auth
flower_1     |     api_auth = import_module(auth_backend)

**Comment by tuanchris** [comment]
Hi Eric, 

The Dockerfile is meant for when you need to build to your own Docker container, that is when the pre-built container does not contain some required packages, for instance. The error you encountered is because the package `flask_bcrypt` was not found. I have added the following snippet to the Dockerfile and it should run fine now.
```
ADD ./requirements.txt /requirements.txt
RUN pip install -r /requirements.txt 
```
Alternatively, you can run `make run` without the need to run `make build` beforehand.
